import type { HouseConfig } from '../types';
import { straightZ } from './streetLayout';

// Avery Ranch tract palette (built ~2004–2005).
const PALETTE = {
  walls: {
    cream: '#e8dcc4',
    tan: '#cdb892',
    sand: '#c8b88c',
    warmGray: '#bbb09b',
    paleBeige: '#e0d4b8',
    softGray: '#cdc6b8',
    biscuit: '#dbcaa6',
    brick: '#b07c5c',
  },
  stone: {
    cream: '#e3d8bf',
    sand: '#d4c4a3',
    limestone: '#dcd2bb',
    blonde: '#cabb96',
  },
  trim: {
    cream: '#f5ecd9',
    soft: '#e8e0cc',
    white: '#f6f1e1',
  },
  roof: {
    brown: '#5d4a37',
    warmBrown: '#6b4a32',
    darkBrown: '#3e2e1f',
    gray: '#4a4a48',
    charcoal: '#3a3838',
  },
  doors: {
    brown: '#4a3623',
    burgundy: '#5a2828',
    black: '#1f1f1f',
    forest: '#2d4a2d',
  },
} as const;

// 7 lots per side along the straight section. South-most slot (t=0) sits just
// north of the bulb; north-most slot (t=1) sits closer to the entry. Spacing:
// t = (i + 0.5) / 7 for i = 0..6 ⇒ midpoints of equal slots. With STRAIGHT
// length 95m, slot pitch is ~13.6m — comfortable for ≤12.5m-wide houses with
// a real ~1m yard gap between neighbors.
const STRAIGHT_SLOTS_PER_SIDE = 7;
const SLOT = (i: number) => straightZ((i + 0.5) / STRAIGHT_SLOTS_PER_SIDE);

// Houses on Royal Tara Cove. Real lat/lng was used to determine which side of
// the street + which slot each address occupies (Nominatim geocoding May 2026).
//
// `source` legend:
//   'verified' = real listing data confirmed the spec
//   'partial'  = some fields confirmed (e.g. sqft only)
//   'inferred' = sensible Avery Ranch tract default — tweak as we remember more
export const HOUSES: HouseConfig[] = [
  // ---- Cul-de-sac bulb (4 houses around the south arc) ----
  // Real bulb angles (math convention) are ~333° (10605), ~4° (10601),
  // ~56° (10600), ~118° (10604). Layout in v4: 10600 anchors the south
  // (90°) at the very end of the cul-de-sac, with the others arranged
  // around it. Lots use neighbor-midpoint wedges, so unequal spacing is fine.
  {
    address: '10605',
    position: { kind: 'bulb', angleDeg: 0 },
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: false,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    sqft: 1697,
    yearBuilt: 2004,
    source: 'verified',
  },
  {
    address: '10601',
    position: { kind: 'bulb', angleDeg: 50 },
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.tan,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    sqft: 2297,
    source: 'verified',
  },
  {
    // The hero house — Zak's family home. Two-story Avery Ranch tract at
    // the very end of the cul-de-sac with the deepest backyard on the street.
    address: '10600',
    position: { kind: 'bulb', angleDeg: 90 },
    width: 18,
    depth: 16,
    stories: 2,
    wallColor: PALETTE.walls.sand,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    isHero: true,
    hipped: true,
    sqft: 2400,
    yearBuilt: 2004,
    source: 'partial',
  },
  {
    address: '10604',
    position: { kind: 'bulb', angleDeg: 135 },
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.paleBeige,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    source: 'inferred',
  },

  // ---- East side of the straight section (odd numbers, 7 houses) ----
  // Slot 0 (closest to bulb) ⇒ slot 6 (north). House widths are capped at
  // 12.5m to leave ~1m of yard between adjacent neighbors (slot pitch ~13.6m).
  // Per-slot Z jitter (±0.5m) breaks the laser-line setback.
  {
    address: '10609',
    position: { kind: 'straight', side: 'east', z: SLOT(0) + 0.4 },
    width: 11,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10613',
    position: { kind: 'straight', side: 'east', z: SLOT(1) - 0.3 },
    width: 12.5,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.warmGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.gray,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10617',
    position: { kind: 'straight', side: 'east', z: SLOT(2) + 0.5 },
    width: 11.5,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.tan,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.burgundy,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10621',
    position: { kind: 'straight', side: 'east', z: SLOT(3) - 0.4 },
    width: 12,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.brick,
    trimColor: PALETTE.trim.cream,
    hasStone: false,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10625',
    position: { kind: 'straight', side: 'east', z: SLOT(4) + 0.3 },
    width: 11,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    sqft: 1594,
    yearBuilt: 2005,
    source: 'verified',
  },
  {
    address: '10629',
    position: { kind: 'straight', side: 'east', z: SLOT(5) - 0.5 },
    width: 12.5,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.softGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.charcoal,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10633',
    position: { kind: 'straight', side: 'east', z: SLOT(6) + 0.4 },
    width: 11.5,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.biscuit,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.forest,
    garageOnLeft: true,
    sqft: 1786,
    source: 'partial',
  },

  // ---- West side of the straight section (even numbers, 7 houses) ----
  {
    address: '10608',
    position: { kind: 'straight', side: 'west', z: SLOT(0) - 0.3 },
    width: 11,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.sand,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10612',
    position: { kind: 'straight', side: 'west', z: SLOT(1) + 0.5 },
    width: 12,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.brick,
    trimColor: PALETTE.trim.cream,
    hasStone: false,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10616',
    position: { kind: 'straight', side: 'west', z: SLOT(2) - 0.4 },
    width: 12.5,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10620',
    position: { kind: 'straight', side: 'west', z: SLOT(3) + 0.3 },
    width: 11.5,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.paleBeige,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10624',
    position: { kind: 'straight', side: 'west', z: SLOT(4) - 0.5 },
    width: 12.5,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.warmGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.gray,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10628',
    position: { kind: 'straight', side: 'west', z: SLOT(5) + 0.4 },
    width: 11,
    depth: 11,
    stories: 1,
    wallColor: PALETTE.walls.biscuit,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.burgundy,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10632',
    position: { kind: 'straight', side: 'west', z: SLOT(6) - 0.3 },
    width: 12,
    depth: 12,
    stories: 2,
    wallColor: PALETTE.walls.softGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.charcoal,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
];
