import type { HouseConfig } from '../types';

// Avery Ranch tract palette (built ~2004–2005). All colors are educated picks
// inspired by typical exteriors in the subdivision; tweak any field below to
// match what you remember of a specific house — that's the whole point of
// this config file.
const PALETTE = {
  walls: {
    cream: '#e8dcc4',
    tan: '#cdb892',
    sand: '#c8b88c',
    warmGray: '#bbb09b',
    paleBeige: '#e0d4b8',
    softGray: '#cdc6b8',
    biscuit: '#dbcaa6',
  },
  stone: {
    cream: '#e3d8bf',
    sand: '#d4c4a3',
    limestone: '#dcd2bb',
    blonde: '#cabb96',
  },
  trim: {
    cream: '#f5ecd9',
    soft: '#e8e0cc',
  },
  roof: {
    brown: '#5d4a37',
    warmBrown: '#6b4a32',
    darkBrown: '#3e2e1f',
    gray: '#4a4a48',
    charcoal: '#3a3838',
  },
  doors: {
    brown: '#4a3623',
    burgundy: '#5a2828',
    black: '#1f1f1f',
    forest: '#2d4a2d',
  },
} as const;

// 10 houses ringed around the cul-de-sac bulb.
//
// Angular layout: 60° gap centered on south (entry road). Houses fill 300° arc
// at 30° per slot, midpoints at 315°, 345°, 15°, 45°, 75°, 105°, 135°, 165°,
// 195°, 225° (math convention: 0° = east, CCW).
//
// Address order goes counter-clockwise from the south-east entry corner:
// 10601, 10605, 10609, 10613, 10617, 10621, 10625, 10629, 10633, 10637.
//
// `source: 'verified'` = real listing data. `'partial'` = some fields confirmed.
// `'inferred'` = reasonable Avery Ranch defaults.
export const HOUSES: HouseConfig[] = [
  {
    address: '10601',
    angleDeg: 315,
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.tan,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    sqft: 2297,
    source: 'verified',
  },
  {
    address: '10605',
    angleDeg: 345,
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: false,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    sqft: 1697,
    yearBuilt: 2004,
    source: 'verified',
  },
  {
    address: '10609',
    angleDeg: 15,
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.sand,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10613',
    angleDeg: 45,
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.warmGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.gray,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10617',
    angleDeg: 75,
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.paleBeige,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.burgundy,
    garageOnLeft: true,
    source: 'inferred',
  },
  {
    address: '10621',
    angleDeg: 105,
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.tan,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10625',
    angleDeg: 135,
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.cream,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.limestone,
    roofColor: PALETTE.roof.warmBrown,
    doorColor: PALETTE.doors.brown,
    garageOnLeft: true,
    sqft: 1594,
    yearBuilt: 2005,
    source: 'verified',
  },
  {
    address: '10629',
    angleDeg: 165,
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.softGray,
    trimColor: PALETTE.trim.soft,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.charcoal,
    doorColor: PALETTE.doors.black,
    garageOnLeft: false,
    source: 'inferred',
  },
  {
    address: '10633',
    angleDeg: 195,
    width: 13,
    depth: 12,
    stories: 1,
    wallColor: PALETTE.walls.biscuit,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.sand,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.forest,
    garageOnLeft: true,
    sqft: 1786,
    source: 'partial',
  },
  {
    address: '10637',
    angleDeg: 225,
    width: 14,
    depth: 13,
    stories: 2,
    wallColor: PALETTE.walls.tan,
    trimColor: PALETTE.trim.cream,
    hasStone: true,
    stoneColor: PALETTE.stone.cream,
    roofColor: PALETTE.roof.brown,
    doorColor: PALETTE.doors.burgundy,
    garageOnLeft: false,
    source: 'partial',
  },
];
